sudo: required
services:
  - docker

before_install:
  - docker build -t sks/sks-react -f Dockerfile.dev .


script:
  - docker run -e CI=true sks/sks-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "sks-docker"
  env: "SksDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-478389293650"
  bucket_path: "sks-docker"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

